CREATE TABLE IF NOT EXISTS files (
	id VARCHAR(40) PRIMARY KEY,
	refId VARCHAR(40) NULL,
	name TEXT NOT NULL,
	extension VARCHAR(100) NOT NULL,
	size  INTEGER NOT NULL,
	status VARCHAR(10) NOT NULL,
	createdOn TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	UNIQUE(name),
	UNIQUE(name, refId)
);